site_name: NIL wiki
site_description: 面向 NIL ，尝试维护一个 wiki
site_author: suoyuan666
# site_url: 
repo_name: NIL_notes
repo_url: https://github.com/suoyuan666/NIL_notes
copyright: Copyright &copy; 2024
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  - content.footnote.tooltips
  font:
    text: Noto Sans
    code: Source Code Pro

nav:
  - 开始:
    - index.md
  - 编程基础:
    - C/C++:
      - programming/c_cpp/lec00/lec00.md
  - Linux 相关:
    - index: 
      - linux/index.md
    - 发行版简介:
      - linux/distro_intro.md
    - 安装指南:
      - linux/install.md
  - 软件使用:
    - tools/git.md
  - 笔记:
    - notes/keep.md
  - 实用工具:
    - Markdown:
      - misc/markdown.md

markdown_extensions:
  - footnotes
