site_name: 计算机基础学习
site_description: 面向初学者，尝试维护一个modern的学习指南
site_author: suoyuan666
# site_url: 
repo_name: learn_c
repo_url: https://github.com/suoyuan666/learn_c
copyright: Copyright &copy; 2024 suoyuan666
theme:
  name: material
  language: zh
  palette:
    primary: white
    accent: red
    scheme: preference
  features:
  - navigation.tabs
  - navigation.tabs.sticky
  - search.suggest
  - search.highlight
  - search.share
  - content.footnote.tooltips
  font:
    text: Noto Sans
    code: Source Code Pro

nav:
  - 开始:
    - index.md
  - 编程基础:
    - programming/lec00.md

markdown_extensions:
  - footnotes